import { fileURLToPath } from 'node:url'

/**
 * Resolves a path relative to this module's directory. The module sits one
 * level below the package root in both layouts — src/paths.ts under tsx and
 * dist/*.js in the production bundle — so the same relative paths work in
 * development, in tests and in the Docker image.
 */
const fromHere = (relative: string): string => fileURLToPath(new URL(relative, import.meta.url))

/** The repository-wide .env (apps/api/../../.env). Optional: missing in Docker. */
export const ROOT_ENV_FILE = fromHere('../../../.env')

/** SQL migrations generated by drizzle-kit. */
export const MIGRATIONS_DIR = fromHere('../drizzle')

/** Where the development fallback database (PGlite) keeps its files. */
export const DEFAULT_PGLITE_DIR = fromHere('../.data/pglite')
